
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Banzai Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release-github:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: maven
    - name: Get the tag (without leading v)
      id: get_tag
      run: echo "release_tag_version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Maven set version
      run: mvn -B versions:set -DnewVersion=${{ env.release_tag_version }}
    - name: Maven build package
      run: mvn -B package -Dmaven.test.skip
    - name: Maven deploy to github mvn repository
      run: mvn -P github-release --batch-mode -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-ossrh:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: maven
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: MAVEN_GPG_KEY
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Get the tag (without leading v)
      id: get_tag
      run: echo "release_tag_version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Maven set version
      run: mvn -B versions:set -DnewVersion=${{ env.release_tag_version }}
    - name: Maven build package
      run: mvn -B package -Dmaven.test.skip
    - name: Maven deploy to maven central mvn repository
      run: mvn -P ossrh-release --batch-mode -B deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}
